name: verification_code_builder
description: Infinitely customizable widget for creating code input forms.
version: 0.1.0
author: RareScrap
homepage: https://github.com/RareScrap/verification_code_builder

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.15.0-nullsafety.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: